### ISSUE TITLE
armv8l

### ISSUE THREAD

**Issue by shoqanebi** [koenvervloesem/bazel-on-arm#3]
build failed every time I try for armv8l
bazel version 3.5.0
all requirements installed successfully

**Comment by koenvervloesem** [comment]
I don't think the patches in this repository are needed anymore for ARM64. You should be able to build Bazel on ARMv8l without them.

Can you give some more information instead of "build failed"? What's your host operating system? What device? What is the output of the build script?

**Comment by shoqanebi** [comment]
OS : kali linux (armhf)
Device : rooted android device
💯 I am sure armv8l is 32

After 3 warnings that build with bazel : bazel not found
build failed no build instruction for arm

**Comment by koenvervloesem** [comment]
Oh right indeed.

The current purpose of this repository is to "build the open source build tool Bazel for ARM on the Raspberry Pi", and it focuses on armhf. It hasn't been tested on other devices, other architectures, or on other distributions than Raspberry Pi OS, as is stated in the system requirements.

If you paste your full output, including the exact warnings and errors, maybe I or someone else can help you further. But you'll have better luck in [Bazel's issue tracker](https://github.com/bazelbuild/bazel/issues). For instance, it seems armv8l [isn't supported yet](https://github.com/bazelbuild/bazel/issues/4968). Maybe start with adding that line in the code before you build. However, Bazel will probably need some other changes too to build on armv8l.

**Comment by shoqanebi** [comment]
![image](https://user-images.githubusercontent.com/45390577/97421781-f465f280-191d-11eb-8b9b-22d3c3ad8a94.png)

**Comment by koenvervloesem** [comment]
It looks like the Bazel build doesn't recognize your CPU architecture correctly. I think it's best to open an issue in Bazel's issue tracker and attach this screenshot, so the Bazel developers can help you.

**Comment by shoqanebi** [comment]
thanks
