### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by KPat421** [koenvervloesem/bazel-on-arm#4]
Hello!
We are trying to install Bazel for Tensorflow 1.0.1 using the info in this repo. We followed the steps and installed Bazel 3.2.0 (earliest available) but when building the package for tensorflow, we receive the following:

Building for the Pi Two/Three, with NEON acceleration
/usr/local/bin/bazel: line 163: /usr/local/lib/bazel/bin/bazel-real: cannot execute binary file: Exec format error
ERROR: The project you're trying to build requires Bazel 3.1.0 (specified in /workspace/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /usr/local/lib/bazel/bin/bazel-3.1.0-linux-armv7l

We are hoping that you can help us solve the issue (potentially with Bazel 3.1.0 for arm). We tried to make the directory specified and move the binary file to it but it results in the same thing. Not sure how to proceed.

Thanks for this, it has been quite helpful regardless.

**Comment by koenvervloesem** [comment]
Have you tried creating a patch for Bazel 3.1.0 to build that version? The process is explained here and you can probably use almost exactly the patch for 3.2.0:

https://github.com/koenvervloesem/bazel-on-arm#patching-other-bazel-versions

**Comment by koenvervloesem** [comment]
I also see that https://github.com/PINTO0309/Bazel_bin has added a Bazel 3.1.0 binary since the last time I looked at that project. That may be worth looking at.

**Comment by KPat421** [comment]
We ended finding a work around that doesn't require manually building Bazel. Thank you so much and we really appreciate you going out of your way to help!
