### ISSUE TITLE
Thanks for the repo

### ISSUE THREAD

**Issue by PeterPirog** [koenvervloesem/bazel-on-arm#5]
Thank You for repo . I spent a lot of time to build bazel for Raspberry Pi 4 unfortunatelly without success.
Your code built bazel in first iteration. Good job.

Now it's time  to learn how tu build python wheels for Raspberry pi 4 becouse becouse some packages I need probably doesn't exist.

Thanks again.

**Comment by koenvervloesem** [comment]
Thanks for your nice words, this frustrating experience is exactly how I started this project :-)
