### ISSUE TITLE
bazel 4.0.0 release is missing pre-built binary

### ISSUE THREAD

**Issue by chrisdunelm** [koenvervloesem/bazel-on-arm#6]
The v4.0.0 release ([https://github.com/koenvervloesem/bazel-on-arm/releases/tag/v4.0.0](https://github.com/koenvervloesem/bazel-on-arm/releases/tag/v4.0.0)) appears to be missing the pre-built bazel binary, which is available for all previous releases.

**Comment by koenvervloesem** [comment]
Sorry, I must have forgotten to upload it. I have fixed it now!

**Comment by chrisdunelm** [comment]
Thanks :)
